# Site settings
title: kuron3k0's Blog
SEOTitle: kuron3k0的博客 | kuron3k0's Blog
header-img: img/home-bg.jpg
email: kuron3ko@protonmail.com
description: "Know it, and then hack it."
keyword: "kuron3k0, Security, CTF, Web"
url: "https://kuron3k0.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     ?
#zhihu_username:     ?
#github_username:    kuron3k0
#twitter_username:   huxpro
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: kuron3k0

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: '50ce382a9aaf855e3bea9d1c2943f700'

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: kuron3k0.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "逆水行舟, 不进则退"
sidebar-avatar: /img/bingo.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "乱序",
#        href: "http://mida.re/"
#    }
#]
